name        : muparser
version     : 2.2.5
release     : 1
source      :
        - https://github.com/beltoforion/muparser/archive/v2.2.5.tar.gz : 0666ef55da72c3e356ca85b6a0084d56b05dd740c3c21d26d372085aa2c6e708
license     : MIT
component   : programming
summary     : muParser is an extensible high performance math expression parser library written in C++. 
description : |
    muParser is an extensible high performance math expression parser library written in C++.
setup      : |   
    %configure --enable-samples=no --enable-shared=yes
build      : |
    %make
install    : |
    %make_install

